#!/usr/bin/env python3
"""Locate metldr's named functions inside another loader.

The loaders are built from the same source, so bodies match closely -- but the
prologue schedule differs, so anchoring on the entry instruction fails. Anchor on
an interior window of mnemonics instead, then walk back to the preceding return
to recover the entry.
"""
import re, sys, collections

def load(path):
    addrs, mnem = [], []
    for l in open(path):
        m = re.match(r'\s*([0-9a-f]+):\t(?:[0-9a-f]{2} ){4}\t(\S+)', l)
        if m:
            addrs.append(int(m.group(1), 16)); mnem.append(m.group(2))
    return addrs, mnem

def index_of(addrs, a):
    lo, hi = 0, len(addrs)
    while lo < hi:
        mid = (lo + hi) // 2
        if addrs[mid] < a: lo = mid + 1
        else: hi = mid
    return lo

def body(addrs, mnem, entry, cap=600):
    i = index_of(addrs, entry)
    out = []
    while i < len(addrs) and len(out) < cap:
        out.append(mnem[i])
        if mnem[i] == 'bi': break
        i += 1
    return out

def find(hay, needle):
    n = len(needle)
    hits = []
    for i in range(len(hay) - n + 1):
        if hay[i:i+n] == needle: hits.append(i)
    return hits

def main():
    ma, mm = load(sys.argv[1])          # reference (metldr)
    aa, am = load(sys.argv[2])          # target
    syms = [l.split() for l in open(sys.argv[3])
            if l.strip() and not l.startswith('#')]
    print(f"{'symbol':<20}{'ref':>8}  {'target':>8}  {'len':>5}  note")
    found = {}
    for s in syms:
        ref = int(s[0], 16); name = s[1]
        b = body(ma, mm, ref)
        if len(b) < 8:
            print(f"  {name:<18}{ref:>8x}  {'-':>8}         reference body too short"); continue
        # window from the middle, away from prologue/epilogue scheduling
        for wlen in (24, 16, 12, 8):
            if len(b) < wlen + 4: continue
            start = max(2, (len(b) - wlen) // 2)
            win = b[start:start+wlen]
            hits = find(am, win)
            if len(hits) == 1:
                # walk back to the instruction after the previous 'bi'
                i = hits[0] - start
                j = i
                while j > 0 and am[j-1] != 'bi': j -= 1
                entry = aa[j]
                found[name] = entry
                print(f"  {name:<18}{ref:>8x}  {entry:>8x}  {len(b):>5}  w={wlen}")
                break
            elif len(hits) > 1:
                continue
        else:
            print(f"  {name:<18}{ref:>8x}  {'-':>8}  {len(b):>5}  no unique window")
    print(f"\nlocated {len(found)}/{len(syms)}")
    if len(sys.argv) > 4:
        with open(sys.argv[4], 'w') as f:
            f.write("# generated by tools/spu-sleigh/xmatch.py -- verify before trusting\n")
            for s in syms:
                if s[1] in found:
                    f.write(f"{found[s[1]]:x}  {' '.join(s[1:])}\n")
        print("wrote", sys.argv[4])

main()
